title: Visual Text Generation and Text Image Processing
description: Website for the Workshop on Visual Text Generation and Text Image Processing
  ---
baseurl: "" # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown
include: ['_pages']
